# Generated by Django 3.2.8 on 2021-10-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время входа')),
                ('end_end', models.DateTimeField(verbose_name='Время выхода')),
                ('position_val', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Объем позиции')),
                ('sell_perc_min', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Минимальный процент продажи')),
                ('sell_perc_max', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Максимальный процент продажи')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Прибыль')),
                ('loss', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Убыток')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='traider.coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['start_time'],
            },
        ),
    ]
