# Generated by Django 3.2.8 on 2021-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0002_rename_end_end_order_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.AddField(
            model_name='order',
            name='result',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_perc_max',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Максимальный процент продажи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_perc_min',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Минимальный процент продажи'),
        ),
    ]
