# Generated by Django 3.2.8 on 2021-10-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0003_auto_20211010_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Traid',
        ),
    ]
