# Generated by Django 3.2.8 on 2021-10-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0004_rename_order_traid'),
    ]

    operations = [
        migrations.AddField(
            model_name='traid',
            name='sell_perc_avrg',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=8, verbose_name='Средний процент продажи'),
        ),
    ]
