# Generated by Django 3.2.8 on 2021-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0005_traid_sell_perc_avrg'),
    ]

    operations = [
        migrations.AddField(
            model_name='traid',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Номер сделки'),
        ),
    ]
