# Generated by Django 3.2.8 on 2021-10-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0006_traid_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traid',
            old_name='sell_perc_avrg',
            new_name='sell_perc_avg',
        ),
    ]
