# Generated by Django 3.2.8 on 2021-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0007_rename_sell_perc_avrg_traid_sell_perc_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traid',
            name='sell_perc_avg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Средний процент продажи'),
        ),
    ]
