# Generated by Django 3.2.8 on 2021-10-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0008_alter_traid_sell_perc_avg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traid',
            options={'ordering': ['-start_time'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
    ]
