# Generated by Django 3.2.8 on 2021-10-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0009_alter_traid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traid',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=8, verbose_name='Номер сделки'),
        ),
    ]
