# Generated by Django 3.2.8 on 2021-10-13 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0011_auto_20211013_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время')),
                ('position_val', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Объем позиции')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Баланс',
                'ordering': ['-date'],
            },
        ),
    ]
