# Generated by Django 3.2.8 on 2021-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0013_auto_20211014_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
    ]
