# Generated by Django 3.2.8 on 2021-10-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0015_balance_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('traid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='traider.traid', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Основание',
                'verbose_name_plural': 'Основания',
                'ordering': ['-name'],
            },
        ),
    ]
