# Generated by Django 3.2.8 on 2021-10-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0016_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='traid',
        ),
        migrations.CreateModel(
            name='EntryReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traider.reason')),
                ('traid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_reasons', to='traider.traid', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Основание для входа',
                'verbose_name_plural': 'Основания для входа',
                'ordering': ['-reason__name'],
            },
        ),
    ]
