# Generated by Django 3.2.8 on 2021-10-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0017_auto_20211017_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traid',
            options={'ordering': ['-number'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
    ]
