# Generated by Django 3.2.8 on 2021-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0019_alter_traid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='usd_equivalent',
            field=models.CharField(blank=True, max_length=50, verbose_name='Эквивалент в USD'),
        ),
    ]
