# Generated by Django 3.2.8 on 2021-10-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0020_balance_usd_equivalent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['name'], 'verbose_name': 'Основание', 'verbose_name_plural': 'Основания'},
        ),
    ]
