# Generated by Django 3.2.8 on 2021-11-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0023_alter_traid_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traid',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='traid',
            name='sell_perc_avg',
        ),
        migrations.RemoveField(
            model_name='traid',
            name='sell_perc_max',
        ),
        migrations.RemoveField(
            model_name='traid',
            name='sell_perc_min',
        ),
        migrations.RemoveField(
            model_name='traid',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_id', models.DecimalField(decimal_places=0, editable=False, max_digits=8, unique=True, verbose_name='Binance order ID')),
                ('deal_type', models.CharField(max_length=250, verbose_name='Тип сделки')),
                ('deal_date', models.DateField()),
                ('deal_time', models.TimeField()),
                ('qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='qty')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='qty')),
                ('quoteQty', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='qty')),
                ('commission', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='qty')),
                ('commissionAsset', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='qty')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='traider.coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-deal_date'],
            },
        ),
    ]
