# Generated by Django 3.2.8 on 2021-11-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0024_auto_20211103_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-deal_date'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
