# Generated by Django 3.2.8 on 2021-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0026_alter_deal_binance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='commission'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='commissionAsset',
            field=models.CharField(max_length=250, verbose_name='commissionAsset'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='quoteQty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='quoteQty'),
        ),
    ]
