# Generated by Django 3.2.8 on 2021-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0027_auto_20211103_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traid',
            name='position_val',
        ),
        migrations.AddField(
            model_name='traid',
            name='buy_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Объем покупки $'),
        ),
        migrations.AddField(
            model_name='traid',
            name='sell_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Объем продажи $'),
        ),
    ]
