# Generated by Django 3.2.8 on 2021-11-03 20:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0028_auto_20211103_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='traid',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='traid',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
