# Generated by Django 3.2.8 on 2021-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0030_auto_20211103_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traid',
            options={'ordering': ['-id'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='commission'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='qty'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='quoteQty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='quoteQty'),
        ),
        migrations.AlterField(
            model_name='traid',
            name='buy_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Объем покупки $'),
        ),
        migrations.AlterField(
            model_name='traid',
            name='result',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='traid',
            name='sell_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Объем продажи $'),
        ),
    ]
