# Generated by Django 3.2.8 on 2021-11-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0031_auto_20211103_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Капитализация')),
                ('minimum_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Минимальная цена')),
                ('is_platform', models.BooleanField(default=False, verbose_name='Явл-ся платформой')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Вес')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='traider.coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='deal',
            name='binance_id',
            field=models.IntegerField(editable=False, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='commissionAsset',
            field=models.CharField(max_length=250, verbose_name='Ком. вал.'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(max_length=250, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='quoteQty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Кол-во подписчиков')),
                ('followers_quality', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Качество подписчиков')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_activities', to='traider.profile', verbose_name='Profile')),
                ('socialnetwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_activities', to='traider.socialnetwork', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Активность в соцсетях',
                'verbose_name_plural': 'Активности в соцсетях',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Вес')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='traider.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Вес')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='traider.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'ordering': ['name'],
            },
        ),
    ]
