# Generated by Django 3.2.8 on 2021-11-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0032_auto_20211106_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='profile',
        ),
        migrations.CreateModel(
            name='TradesOnExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Вес')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_on_exchanges', to='traider.exchange', verbose_name='Exchange')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='traider.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Активная биржа',
                'verbose_name_plural': 'Активные биржи',
            },
        ),
        migrations.CreateModel(
            name='ActiveInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Вес')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='traider.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Активный Инвестор',
                'verbose_name_plural': 'Активные Инвесторы',
                'ordering': ['name'],
            },
        ),
    ]
