# Generated by Django 3.2.8 on 2021-11-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0033_auto_20211106_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeinvestor',
            options={'verbose_name': 'Активный Инвестор', 'verbose_name_plural': 'Активные Инвесторы'},
        ),
        migrations.RemoveField(
            model_name='activeinvestor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activeinvestor',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='tradesonexchange',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tradesonexchange',
            name='weight',
        ),
        migrations.AddField(
            model_name='activeinvestor',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_investors', to='traider.investor', verbose_name='Investor'),
        ),
    ]
