# Generated by Django 3.2.8 on 2021-11-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0034_auto_20211106_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialactivity',
            name='socialnetwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_activities', to='traider.socialnetwork', verbose_name='SocialNetwork'),
        ),
    ]
