# Generated by Django 3.2.8 on 2021-11-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0035_alter_socialactivity_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokenomic',
            field=models.TextField(blank=True, verbose_name='Токеномика'),
        ),
        migrations.AlterField(
            model_name='activeinvestor',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_investors', to='traider.investor', verbose_name='Инвестор'),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='socialnetwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_activities', to='traider.socialnetwork', verbose_name='Соцсеть'),
        ),
        migrations.AlterField(
            model_name='tradesonexchange',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_on_exchanges', to='traider.exchange', verbose_name='Биржа'),
        ),
    ]
