# Generated by Django 3.2.8 on 2021-11-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0036_auto_20211106_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traid',
            name='buy_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Объем покупки $'),
        ),
        migrations.AlterField(
            model_name='traid',
            name='result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='traid',
            name='sell_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Объем продажи $'),
        ),
    ]
