# Generated by Django 3.2.8 on 2021-11-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0037_auto_20211107_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_id', models.IntegerField(editable=False, unique=True, verbose_name='Order ID')),
                ('operation_type', models.CharField(max_length=250, verbose_name='Тип')),
                ('operation_date', models.DateField(verbose_name='Дата')),
                ('operation_time', models.TimeField(verbose_name='Время')),
                ('qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Цена')),
                ('quoteQty', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Сумма')),
                ('commission', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Комиссия')),
                ('commissionAsset', models.CharField(max_length=250, verbose_name='Ком. вал.')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='traider.coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
