# Generated by Django 3.2.8 on 2021-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0043_rename_candidate_type_candidate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['symbol'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('consoludating', 'Консолидация'), ('breakingout', 'Пробитие')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('4h', '4h'), ('1h', '1h'), ('30min', '30min'), ('15min', '15min')], max_length=15, verbose_name='Time frame'),
        ),
    ]
