# Generated by Django 4.0.1 on 2022-01-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0049_remove_profile_coin_remove_socialactivity_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('name',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
        migrations.CreateModel(
            name='TraidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traider.image')),
                ('traid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='traider.traid', verbose_name='сделка')),
            ],
        ),
    ]
