# Generated by Django 4.0.1 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0050_alter_image_options_rename_title_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traid',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
