# Generated by Django 4.0.1 on 2022-01-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0051_remove_traid_image_alter_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traidimage',
            old_name='image',
            new_name='screenshot',
        ),
    ]
