# Generated by Django 4.0.1 on 2022-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0052_rename_image_traidimage_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traidimage',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='traidimage',
            name='attached_file',
            field=models.ImageField(blank=True, upload_to='images/traids/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='traidimage',
            name='name',
            field=models.CharField(default='image', max_length=500, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
