# Generated by Django 4.0.1 on 2022-02-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0054_traid_attached_file_delete_traidimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traid',
            name='attached_file',
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.ImageField(blank=True, upload_to='images/traids/', verbose_name='Screen shot')),
                ('traid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='traider.traid', verbose_name='сделка')),
            ],
        ),
    ]
