# Generated by Django 4.0.1 on 2022-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0055_remove_traid_attached_file_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='filename',
            field=models.CharField(blank=True, max_length=50, verbose_name='Filename'),
        ),
    ]
