# Generated by Django 3.2.12 on 2022-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0057_traid_result_minus_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=50, verbose_name='Торговая пара')),
                ('rule', models.CharField(choices=[('lte', '<='), ('gte', '>=')], default='lte', max_length=15, verbose_name='Павило')),
                ('target_price', models.FloatField(verbose_name='Target price')),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Done')], default='new', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Trackings',
                'ordering': ['pair'],
            },
        ),
    ]
