# Generated by Django 3.2.12 on 2022-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0059_remove_traid_result_minus_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('4h', '4h'), ('1h', '1h'), ('30min', '30min'), ('15min', '15min'), ('5min', '5min')], max_length=15, verbose_name='Time frame'),
        ),
    ]
