# Generated by Django 3.2.12 on 2022-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0060_alter_candidate_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='data',
            field=models.TextField(blank=True, verbose_name='Candles data'),
        ),
    ]
