# Generated by Django 4.0.3 on 2022-03-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0061_candidate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traid',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traids', to='traider.coin', verbose_name='Монета'),
        ),
    ]
