# Generated by Django 4.0.3 on 2023-02-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0067_alter_partnerprofit_profit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Имя')),
                ('percentage', models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Доля в процентах от общего дохода')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Трейдер',
                'verbose_name_plural': 'Трейдеры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='start_deposit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Начальный депозит партнера'),
        ),
        migrations.CreateModel(
            name='TraiderProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_date', models.DateField(verbose_name='Дата')),
                ('profit', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Прибыль')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('traider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profits', to='traider.traider', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Прибыль трейдера',
                'verbose_name_plural': 'Прибыли трейдера',
                'ordering': ['-profit_date'],
            },
        ),
    ]
