# Generated by Django 4.0.3 on 2023-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0068_traider_partner_start_deposit_traiderprofit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerprofit',
            options={'ordering': ['-profit_date'], 'verbose_name': 'Прибыль партнеров', 'verbose_name_plural': 'Прибыль партнеров'},
        ),
        migrations.AlterModelOptions(
            name='traiderprofit',
            options={'ordering': ['-profit_date'], 'verbose_name': 'Прибыль трейдера', 'verbose_name_plural': 'Прибыль трейдера'},
        ),
        migrations.AddField(
            model_name='partner',
            name='deposit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Текущий депозит партнера'),
        ),
        migrations.AddField(
            model_name='traider',
            name='deposit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Текущий депозит трейдера'),
        ),
    ]
