# Generated by Django 4.0.3 on 2023-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traider', '0070_alter_partner_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='deposit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Текущий депозит'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='start_deposit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50, verbose_name='Начальный депозит'),
        ),
    ]
